name: MooScrollDepth
author: aronbudinszky
category: Utilities
tags: [google analytics, analytics, scroll, scrolling]
#docs: http://devthought.com/projects/mootools/textboxlist/
#demo: http://devthought.com/wp-content/project/mootools/textboxlist/Demo/